/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./src/components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElList: typeof import('element-plus/es')['ElList']
    ElListItem: typeof import('element-plus/es')['ElListItem']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logos: typeof import('./src/components/Logos.vue')['default']
    MetricsPanel: typeof import('./src/components/MetricsPanel.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    StatusPanel: typeof import('./src/components/StatusPanel.vue')['default']
  }
}
